name: "Continuous Integration"

on:
  push:
    branches:
      - 'master'
      - '3.0'
      - '2.0'
      - '1.0'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      oracle:
        image: deepdiver/docker-oracle-xe-11g:2.0
        ports:
          - 49160:22
          - 1521:1521

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1, 8.2, 8.3, 8.4]
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} - STABILITY ${{ matrix.stability }}

    env:
        key: ${{ matrix.php }}-v1
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, memcached, oci8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.extensions }}
            key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
            path: ${{ steps.extcache.outputs.dir }}
            key: ${{ steps.extcache.outputs.key }}
            restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          tools: composer:v2
          coverage: none

      - name: Setup Memcached
        uses: niden/actions-memcached@v7

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Run Tests
        run: vendor/bin/phpunit
